(* TEST
  flags = "-dlambda -dcanonical-ids";
  expect;  *)


type t = ..
;;
[%%expect{|
0
type t = ..
|}]

type t +=
  | A
  | B
  | C of int
  | D of float
  | E of t * int
;;
[%%expect{|
(let
  (A/0 = (makeblock 248 "A" (caml_fresh_oo_id 0) 65)
   B/0 = (makeblock 248 "B" (caml_fresh_oo_id 0) 66)
   C/0 = (makeblock 248 "C" (caml_fresh_oo_id 0) 67)
   D/0 = (makeblock 248 "D" (caml_fresh_oo_id 0) 68)
   E/0 = (makeblock 248 "E" (caml_fresh_oo_id 0) 69))
  (seq (apply (field_mut 1 (global Toploop!)) "A/282" A/0)
    (apply (field_mut 1 (global Toploop!)) "B/283" B/0)
    (apply (field_mut 1 (global Toploop!)) "C/284" C/0)
    (apply (field_mut 1 (global Toploop!)) "D/285" D/0)
    (apply (field_mut 1 (global Toploop!)) "E/286" E/0)))
type t += A | B | C of int | D of float | E of t * int
|}]

(* Check that identical dispatch tables generated by a dynamic switch
   are merged by the compiler *)

let rec foo1 x =
  (match x with
  | A -> "A"
  | B -> "B"
  | C i -> Printf.sprintf "C(%d)" i
  | D f -> Printf.sprintf "D(%f)" f
  | E (t, i) -> Printf.sprintf "E(%s, %d)" (foo1 t) i
  | _ -> "unknown") [@dynamic]

and foo2 x =
  (match x with
  | A [@dynamic] -> 1
  | B -> 2
  | C i -> i
  | D f -> int_of_float f
  | E (t, i) -> (foo2 t) + i
  | _ -> 0) [@dynamic]
;;
[%%expect{|
(let
  (E/0 = (apply (field_mut 0 (global Toploop!)) "E/286")
   D/0 = (apply (field_mut 0 (global Toploop!)) "D/285")
   C/0 = (apply (field_mut 0 (global Toploop!)) "C/284")
   B/0 = (apply (field_mut 0 (global Toploop!)) "B/283")
   A/0 = (apply (field_mut 0 (global Toploop!)) "A/282")
   tag_table/0 =
     (apply (field_imm 1 (global CamlinternalExtension!))
       (makeblock 0 (makeblock 0 A/0 5)
         (makeblock 0 (makeblock 0 B/0 4)
           (makeblock 0 (makeblock 0 C/0 3)
             (makeblock 0 (makeblock 0 D/0 2)
               (makeblock 0 (makeblock 0 E/0 1) 0)))))))
  (letrec
    (foo1/0
       (function x/0
         (switch (apply tag_table/0
                   (switch* x/0
                    case tag 0: (field_int 1 (field_imm 0 x/0))
                    case tag 248: (field_int 1 x/0)) never_inline)
          case int 5: "A"
          case int 4: "B"
          case int 3:
           (apply (field_imm 3 (global Stdlib__Printf!))
             [0: [11: "C(" [4: 0 0 0 [12: ')' 0]]] "C(%d)"]
             (field_imm 1 x/0))
          case int 2:
           (apply (field_imm 3 (global Stdlib__Printf!))
             [0: [11: "D(" [8: [0: 0 0] 0 0 [12: ')' 0]]] "D(%f)"]
             (field_imm 1 x/0))
          case int 1:
           (apply (field_imm 3 (global Stdlib__Printf!))
             [0:
              [11: "E(" [2: 0 [11: ", " [4: 0 0 0 [12: ')' 0]]]]] "E(%s, %d)"]
             (apply foo1/0 (field_imm 1 x/0)) (field_imm 2 x/0))
          default: "unknown"))
      foo2/0
        (function x/1 : int
          (switch (apply tag_table/0
                    (switch* x/1
                     case tag 0: (field_int 1 (field_imm 0 x/1))
                     case tag 248: (field_int 1 x/1)) never_inline)
           case int 5: 1
           case int 4: 2
           case int 3: (field_imm 1 x/1)
           case int 2: (int_of_float (field_imm 1 x/1))
           case int 1: (+ (apply foo2/0 (field_imm 1 x/1)) (field_imm 2 x/1))
           default: 0)))
    (seq (apply (field_mut 1 (global Toploop!)) "foo1" foo1/0)
      (apply (field_mut 1 (global Toploop!)) "foo2" foo2/0))))
val foo1 : t -> string = <fun>
val foo2 : t -> int = <fun>
|}]
